### ISSUE TITLE
vh_gui --install

### ISSUE THREAD

**Issue by DooMFeaR** [Verlihub/verlihub-1.0.0#33]
Hello again! I got some problems when I'm trying to install verlihub with the command "vh_gui --install"

 <code>-- ERROR: This script requires dialog to function, please consider installing it or use cli scripts instead (vh).</code>

**Comment by omh-WiZaRd** [comment]
Hi,
You have to install dialogs :)
Simply use apt-get install dialog or yum install dialog, depending on the linux flawor that you use. 

Sent from my BlackBerry® smartphone provided by Telekom Romania

-----Original Message-----

**Comment by DooMFeaR** [comment]
@omh-WiZaRd Thank you,but I've installed it using <b> vh --install </b>

**Comment by RoLex** [comment]
This issue was moved to Verlihub/verlihub#68
