### ISSUE TITLE
Errors when building without GeoIP

### ISSUE THREAD

**Issue by vovochka404** [Verlihub/verlihub-1.0.0#36]
GeoIP isn't marked as required:
```cmake
Find_Package(GeoIP)
```
But when trying to build without geoip cmake complains on undefined variables
```txt
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
GEOIP_INCLUDE_DIR (ADVANCED)
   used as include directory in directory /root/test/verlihub
   used as include directory in directory /root/test/verlihub/src
   used as include directory in directory /root/test/verlihub/src
   used as include directory in directory /root/test/verlihub/src
   used as include directory in directory /root/test/verlihub/src
   used as include directory in directory /root/test/verlihub/plugins/plugman
   used as include directory in directory /root/test/verlihub/plugins/forbid
   used as include directory in directory /root/test/verlihub/plugins/chatroom
   used as include directory in directory /root/test/verlihub/plugins/iplog
   used as include directory in directory /root/test/verlihub/plugins/isp
   used as include directory in directory /root/test/verlihub/plugins/messenger
   used as include directory in directory /root/test/verlihub/plugins/stats
   used as include directory in directory /root/test/verlihub/plugins/replacer
   used as include directory in directory /root/test/verlihub/plugins/floodprot
   used as include directory in directory /root/test/verlihub/po
   used as include directory in directory /root/test/verlihub/po
GEOIP_LIBRARIES (ADVANCED)
    linked by target "libverlihub" in directory /root/test/verlihub/src

-- Configuring incomplete, errors occurred!
```

**Comment by shurshur** [comment]
Which version of cmake you use?

**Comment by vovochka404** [comment]
CentOS Linux release 7.0.1406 (Core)
Cmake 2.8.11

**Comment by KhArtNJava** [comment]
CentOS 6

cmake version 2.8.12.2


--
-- To change any of these options, override them using -D{OPTION_NAME} on the command line.
-- To build and install Verlihub, run "make" and "make install"
--
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
GEOIP_INCLUDE_DIR (ADVANCED)
   used as include directory in directory /home/apps/verlihub-1.0.0-rc4
   used as include directory in directory /home/apps/verlihub-1.0.0-rc4/src
   used as include directory in directory /home/apps/verlihub-1.0.0-rc4/src
   used as include directory in directory /home/apps/verlihub-1.0.0-rc4/src
   used as include directory in directory /home/apps/verlihub-1.0.0-rc4/src
   used as include directory in directory /home/apps/verlihub-1.0.0-rc4/plugins/plugman
   used as include directory in directory /home/apps/verlihub-1.0.0-rc4/plugins/lua
   used as include directory in directory /home/apps/verlihub-1.0.0-rc4/plugins/forbid
   used as include directory in directory /home/apps/verlihub-1.0.0-rc4/plugins/chatroom
   used as include directory in directory /home/apps/verlihub-1.0.0-rc4/plugins/iplog
   used as include directory in directory /home/apps/verlihub-1.0.0-rc4/plugins/isp
   used as include directory in directory /home/apps/verlihub-1.0.0-rc4/plugins/messenger
   used as include directory in directory /home/apps/verlihub-1.0.0-rc4/plugins/stats
   used as include directory in directory /home/apps/verlihub-1.0.0-rc4/plugins/replacer
   used as include directory in directory /home/apps/verlihub-1.0.0-rc4/plugins/floodprot
   used as include directory in directory /home/apps/verlihub-1.0.0-rc4/po
   used as include directory in directory /home/apps/verlihub-1.0.0-rc4/po
GEOIP_LIBRARIES (ADVANCED)
    linked by target "libverlihub" in directory /home/apps/verlihub-1.0.0-rc4/src

-- Configuring incomplete, errors occurred!
See also "/home/apps/verlihub-1.0.0-rc4/build/CMakeFiles/CMakeOutput.log".
See also "/home/apps/verlihub-1.0.0-rc4/build/CMakeFiles/CMakeError.log".

**Comment by shurshur** [comment]
Closed. Please reopen if issue is not fixed yet.

**Comment by RoLex** [comment]
This issue was moved to Verlihub/verlihub#73
